kind: Pod
apiVersion: v1
metadata:
  name: myservicea
  labels:
    app: myservicea
spec:
  containers:
    - name: myservicea-app
      image: nginx
      
---

kind: Service
apiVersion: v1
metadata:
  name: myservice-service
spec:
  selector:
    app: myservicea
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservicea
spec:
  rules:
  - host: {{ .Values.lb_dns_name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myservice-service
            port:
              number: 80
  ingressClassName: nginx
